#!/bin/sh

##
# pingtest - ping with random sizes
#
# Copyright (C) 2010 Felipe Balbi <felipe.balbi@nokia.com>
#
# This file is part of the USB Verification Tools Project
#
# USB Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public Liicense as published by
# the Free Software Foundation, either version 3 of the license, or
# (at your option) any later version.
#
# USB Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with USB Tools. If not, see <http://www.gnu.org/licenses/>.
##

num=$1

if [ -z $num ]
then
	num=10000
fi

sudo ifconfig usb0 >/dev/null
sleep 1;
sudo ifconfig usb0 192.168.2.14

if ! `ping -I usb0 192.168.2.15 -c 1 >/dev/null 2>&1`
then
	printf "NO INTERFACE\n" >/dev/stderr
	exit 1
fi

RANDOM=1024

for i in `seq 1 $num`; do
	size=$RANDOM
	printf "pinging with size $size     \t\t"
	if ! `ping -c 1 192.168.2.15 -s $size >/dev/null 2>&1`; then
		printf "FAILED\n"
		break
	fi
	printf "PASSED\n"
done

