#!/bin/sh

##
# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2010-2016 Felipe Balbi <felipe.balbi@linux.intel.com>
##

random()
{
	size=$(dd if=/dev/urandom count=1 2>/dev/null|cksum|
	cut -f1 -d" "|tr '-' '\0')
	size=$(expr $size % 60000)
}

num=$1

if [ -z $num ]
then
	num=10000
fi

while ! sudo ifconfig usb0 >/dev/null 2>&1; do
	printf "waiting for usb0\n"
	sleep 1;
done

sudo ifconfig usb0 192.168.2.14

if ! ping -I usb0 192.168.2.15 -c 1 >/dev/null 2>&1
then
	printf "NO INTERFACE\n" >/dev/stderr
	exit 1
fi

for i in $(seq 1 $num); do
	random
	printf "%d: \t pinging with size %-27d" $i $size
	if ! ping -c 6 192.168.2.15 -s $size -q -i 0 >/dev/null 2>&1; then
		printf "FAILED\n"
		break
	fi
	printf "PASSED\n"
done

